#%RAML 1.0 Library
usage: Library of DataTypes
types:
  Error: !include ../datatypes/Error.raml
  Hotel: !include ../datatypes/Hotel.raml
  Registration: !include ../datatypes/Registration.raml
  Booking: !include ../datatypes/Booking.raml
  Status: !include ../datatypes/Status.raml   


