#%RAML 1.0
title: BookMyHotelAPI
baseUri: http://bookmyhotel.com
mediaType: 
  - application/json


uses:
  traitsLib: libraries/TraitsLibrary.raml
  resTypesLib:  libraries/ResourceTypesLibrary.raml
  dataTypesLib: libraries/DataTypesLibrary.raml



/registrations:
  type: resTypesLib.collection
  get:
  post:
  /{registrationId}:
    type: resTypesLib.member
    get:
    patch:
    delete:
/hotels:
  type: resTypesLib.collection
  get:
    queryParameters:
      city:
        required: false
      state:
        required: false
      country:
        required: false
  post:
  /{hotelId}:
    type: resTypesLib.member
    get:
    patch:
    delete:
    /bookings:
      description: Bookings of specific Hotel
      type: resTypesLib.collection
      get:
        
/bookings:
  type: resTypesLib.collection
  get:
  post:
  /{bookingId}:
    type: resTypesLib.member
    get:
    patch:
    delete: